name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release and Archive Native
    runs-on: macos-12
    timeout-minutes: 30
    permissions:
      issues: write
      contents: write
      deployments: write
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"

      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: "Import Certificate: Release"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.RELEASE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.RELEASE_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Expose release info to actions
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Cache mint modules
        uses: actions/cache@v2
        env:
          cache-name: cache-mint-v2
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ env.cache-name }}-${{ hashFiles('Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-${{ env.cache-name }}-
      - name: Install mint and packages
        run: brew install mint && mint bootstrap
      - name: Cache DerivedData
        uses: actions/cache@v2
        env:
          cache-name: release-derived-data-v1
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Cache SPM modules
        uses: actions/cache@v2
        env:
          cache-name: cache-spm-v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ env.cache-name }}-${{ hashFiles('Pareto Updater.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ env.cache-name }}-
      - name: Patch version from release
        run: |
          sed -E -i '' 's/MARKETING_VERSION = .*;/MARKETING_VERSION = ${{ steps.release.outputs.tag }};/g' Pareto\ Updater.xcodeproj/project.pbxproj
      - name: "Archive for dist"
        run: set -o pipefail && make archive-release | mint run xcbeautify

      - name: Compress app for storage
        run: ditto -V -c -k --keepParent Export/Pareto\ Updater.app ParetoUpdater.app.zip

      - name: Upload App to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ParetoUpdater.app
          path: ParetoUpdater.app.zip

      - name: Build dmg for release
        run: npm install --global create-dmg && make dmg

      - name: "Notarize Release Build"
        run: xcrun notarytool submit ParetoUpdater.dmg --password ${{ secrets.NOTARIZATION_PASSWORD }} --apple-id ${{ secrets.NOTARIZATION_USERNAME }} --team-id PM784W7B8X --progress --wait

      - name: Upload DMG to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ParetoUpdater.dmg
          path: ParetoUpdater.dmg

      - name: "Staple Release DMG"
        run: for i in {1..3}; do xcrun stapler staple ParetoUpdater.dmg && break || sleep 15; done

      - name: Release DMG
        uses: softprops/action-gh-release@v1
        with:
          files: ParetoUpdater.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: rm -f ParetoUpdater.app.zip

      - name: Compress app for release
        run: ditto -V -c -k --keepParent Export/Pareto\ Updater.app ParetoUpdater.app.zip

      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: ParetoUpdater.app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install sentry-cli
        run: brew install getsentry/tools/sentry-cli
      - name: "Upload debug symbols"
        run: make sentry-debug-upload
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
